### ISSUE TITLE
Try literalify to allow some js to be included via CDN

### ISSUE THREAD

**Issue by webmasterkai** [OOKB/rg-client-app#161]
Our js bundle is large and it would be nice to share some portions of it between HTML and JS App. React is the obvious big one. This came up thinking about how best to solve #159  http://pluma.github.io/literalify/

**Comment by webmasterkai** [comment]
Still nice to have but it'd be better to spend time on new app code.

**Comment by bjornmeansbear** [comment]
Yeah. So shall we just close it out then?
