### ISSUE TITLE
17) Content - Group the percentages with the word always to avoid them breaking apart?

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/rg-client-app#255]
They don’t like how it happens on other parts of the site. While we don’t want to do a line break for each like we did in the price list, at the very least they should group together. Is this possible? I know there are things such as No-break space elements, but I’m not sure how we’d go about swapping this in.

**Comment by webmasterkai** [comment]
Can you give me some specific examples?

**Comment by bjornmeansbear** [comment]
My previous explanation is not enough for me to understand what I was even asking orginally.
