### ISSUE TITLE
Passementerie in detail view no longer are getting their "margin-top" correctly set

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/rg-client-app#274]
this line: https://github.com/OOKB/rg-client-app/blob/master/app/views/detail/buttons.coffee#L53

doesn't appear to be outputting correctly anymore, rendered HTML on the site just sees style="margin-top:-NaNpx;"

**Comment by bjornmeansbear** [comment]
Okay! I think I've figured out what might be going on (sort of)

https://github.com/OOKB/rg-client-app/blob/master/app/views/detail/buttons.coffee#L53

Line 53 of the app/views/detail/buttons.coffee file doesn't find the `.height` value, and so produces the `NaN` instead of a numeric value. There is no standard height however for the passementerie, so we need it to ask for the height each time a new image is loaded (or a new size is swapped in as that will change the height as well)

**Comment by webmasterkai** [comment]
i'll have to see why the height isn't sent from the db

**Comment by bjornmeansbear** [comment]
We still need to resolve this. It's billable, since the new "wide" passementerie's were the cause (or at least the thing that caused it to be noticed)

**Comment by webmasterkai** [comment]
I tried the easy things without any success. There are a lot of different things that make this difficult.

**Comment by bjornmeansbear** [comment]
So we can know the height/width ratio for each image then, and then apply this... okay. So.... next step is the dropbox » to whereever we want to keep them... new issue, new day?

**Comment by bjornmeansbear** [comment]
solved by dece00219b9017721e808e83c19c7bd11f06304c and 82798437675acd74eaddb1b51101e77dec80206c and 6c5c098972d7fdce1b4dbf4a715779adac0efa8b and 3a513ab267b2966535cb5727d1f389c9396a1302
