### ISSUE TITLE
Images 91036-01 thru 91036-06 have had their images updated

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/rg-client-app#278]
I replaced their images with new ones in dropbox, but that has't appeared to trickle down to the site yet.

They went from horizontal stripes to vertical stripes — correct view is vertical, they are still showing as horizontal (http://www.rogersandgoffigon.com/#collection/textile/12/91036/p1)

@webmasterkai will you please make it so :+1:

**Comment by webmasterkai** [comment]
They will update as the CDN cache expires.
http://rogersandgoffigon.imgix.net/normal/91036-02.jpg?w=1536
http://rogersandgoffigon.imgix.net/normal/91036-03.jpg?w=1536
http://rogersandgoffigon.imgix.net/normal/91036-04.jpg?w=1536
http://rogersandgoffigon.imgix.net/normal/91036-05.jpg?w=1536
http://rogersandgoffigon.imgix.net/normal/91036-06.jpg?w=1536

**Comment by webmasterkai** [comment]
If it's an emergency I can manually purge the cache for the smaller sizes of each one.

**Comment by bjornmeansbear** [comment]
Not an emergency. Thx for checking.
