### ISSUE TITLE
fix typo for passementerie folder on B2 image storage

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/rg-client-app#284]
should be `passementerie` instead of `passementrie`

**Comment by bjornmeansbear** [comment]
I couldn't figure out an easy way to move the files other than manually (which I'm happy to do if that is the best option), and "rename" isn't an option for me w/ cyberduck.

And I didn't know where to update the image urls on the rg site itself...

**Comment by webmasterkai** [comment]
There are two different versions of that folder. It's intentional, needs to copy what was in dropbox for now. This will be when we change systems at some point in the future.
