### ISSUE TITLE
Search field does not accept special characters

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/rg-client-app#287]
Search field on RG doesn’t accept accents, etc. but they have a new fabric to introduce, 710009 — Linné which has an accented é

typing linne in the search field doesn’t return results! and I can’t type a é — what can we do to solve? (billable project!)

http://www.rogersandgoffigon.com/#collection/textile/12/710009/p1 are the fabrics, but if you enter linn you get them, plus some other things, and if you type linne you get nothing
http://www.rogersandgoffigon.com/#collection/textile/12/linn/p1
http://www.rogersandgoffigon.com/#collection/textile/12/linne/p1

**Comment by webmasterkai** [comment]
There was a reason it was being filtered out. Not sure what that reason was...
