### ISSUE TITLE
Full Patterns not loading

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/rg-client-app#288]
I am encountering an issue in the detail view where the full pattern images src’s @aren’t properly printing out when you toggle the view to them.
http://www.rogersandgoffigon.com/#detail/92536/01 

click view pattern, it toggles the view, but the src for the image is (unknown)

it has its image on imgix, so that isn't the issue
http://rogersandgoffigon.imgix.net/far/92536-01.jpg

Any ideas?

**Comment by webmasterkai** [comment]
This is working fine for me.

**Comment by bjornmeansbear** [comment]
Hmm.
Yeah, works in Chrome, Safari, internet explorer (via browserstack) — but not in FF; no errors in console in FF though, so not sure what the issue there might be.

RG analytics are mostly Safari and Chrome users, FF users are 3rd most populace; making up 9% of visitors — by narrowing down on FF And Location, I'm only a few of the visits, there seems to be two  New York sales associates that use FF and visit the site everyday... 

I'll keep monkeying around and see if I can trigger an actual error to let me know what's up.

**Comment by webmasterkai** [comment]
Works in Firefox too. Just needed to wait 7 seconds for it to load completely.

**Comment by bjornmeansbear** [comment]
It never loads in FF for me. It's not just a waiting issue.
But like I said, there isn't an error that triggers in the Console that I can use to help solve this, so I guess it should just stay closed if it appears its working for others…
